spring:
  application:
    name: kbstar-wallet-msa

  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      username: postgres
      password: postgres
    second:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: "jdbc:mysql://localhost/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&tinyInt1isBit=false"
#      username: eggseller
#      password: "387421"
      driver-class-name: org.postgresql.Driver
      jdbc-url: "jdbc:postgresql://localhost:5432/second"
      username: postgres
      password: postgres
    
  security:
    user:
      name: admin
      password: admin
jasypt:
  encryptor:
    bean: jasyptStringEncryptor      

logging:
  level:
    root: info
    com.bangahu.main: debug
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] : %msg%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] : %msg%n"

---
properties:
  message:
    test: abc-123
    