spring:
  application:
    name: kbstar-wallet-msa

  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      username: postgres
      password: postgres
    second:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: "jdbc:mysql://localhost/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&tinyInt1isBit=false"
#      username: eggseller
#      password: "387421"
      driver-class-name: org.postgresql.Driver
      jdbc-url: "jdbc:postgresql://localhost:5432/second"
      username: postgres
      password: postgres

  jta:
    atomikos:
      datasource:
        master:
          unique-resource-name: master
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            serverName: localhost
            portNumber: 5432
            databaseName: postgres
            user: postgres
            password: postgres
          #initQuery: select 1
          testOnBorrow: true
          validationQuery: select 1
          defaultAutoCommit: false
          max-pool-size: 10
          min-pool-size: 3
          reap-timeout: 60
        second:
          unique-resource-name: second
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            serverName: localhost
            portNumber: 3306
            databaseName: test
            user: eggseller
            password: 387421
          #initQuery: select 1
          testOnBorrow: true
          validationQuery: select 1
          defaultAutoCommit: false
          max-pool-size: 10
          min-pool-size: 3
          reap-timeout: 60
              
  security:
    user:
      name: admin
      password: admin
jasypt:
  encryptor:
    bean: jasyptStringEncryptor      

logging:
  level:
    root: info
    com.bangahu.main: debug
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] : %msg%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] : %msg%n"

---
properties:
  message:
    test: abc-123
    error: noproblem
    job:
      title: dev
      period: forever
      tasks:
        clean: room
        wash: dish
    